<x-contenedor-aplicacion title="Formato final | Administración de proyectos" active="" :navegacion="$navegacion" :role-name="$roleName">
    <a href="{{ $regreso['url'] }}" class="mb-4 inline-flex items-center gap-2 rounded border border-[#155AA3] bg-white px-4 py-2 text-sm font-bold text-[#155AA3]">← {{ $regreso['etiqueta'] }}</a>
    <h2 class="text-2xl font-bold text-[#0D376D]">Formato final</h2><p class="mt-2 text-sm text-slate-600">{{ $proyecto->titulo }} · {{ $guia->nombre }}</p>
    <x-mensajes-formulario />
    @if($cierre)<section class="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-5"><h3 class="font-bold">Cierre del proyecto: {{ ucfirst($cierre->estado) }}</h3><p class="mt-2 text-sm">{{ $cierre->estado === 'cerrado' ? 'El docente líder registró el cierre y su constancia de pendientes.' : 'El seguimiento del cierre y las prórrogas corresponde al docente líder.' }}</p>@if($puedeResolverCierre)<a href="{{ route('docente-lider.cierres.mostrar', $proyecto) }}" class="mt-3 inline-block font-bold text-[#155AA3] underline">Ver cierre y prórrogas</a>@endif</section>@endif
    <div class="mt-5 rounded-lg border bg-white p-5"><h3 class="font-bold">Estado de aprobaciones</h3>
        @if($pendientes)<ul class="mt-3 list-disc space-y-1 pl-5 text-sm text-amber-800">@foreach($pendientes as $pendiente)<li>{{ $pendiente }}</li>@endforeach</ul>@else<p class="mt-3 text-sm text-emerald-800">Todas las entregas cuentan con las aprobaciones firmadas requeridas.</p>@endif
        <form method="POST" action="{{ route('documentos.generar', $proyecto) }}" class="mt-4">@csrf<button @disabled(count($pendientes) > 0) class="rounded bg-[#155AA3] px-4 py-2 font-bold text-white disabled:opacity-40">Generar PDF final</button></form>
    </div>
    <h3 class="mt-6 font-bold">Borrador con los datos actuales</h3><p class="mt-1 text-sm text-slate-500">Esta vista se actualiza con el proyecto. Los PDF emitidos de abajo conservan su contenido original.</p><iframe title="Borrador con los datos actuales" src="{{ route('documentos.preview', $proyecto) }}" class="mt-3 h-[70vh] w-full rounded border bg-white"></iframe>
    <div class="mt-5 rounded-lg border bg-white p-5"><h3 class="font-bold">Documentos emitidos</h3><p class="mt-1 text-sm text-slate-500">Cada archivo conserva las firmas y los datos con los que se emitió.</p>@forelse($documentos as $documento)<a href="{{ route('documentos.descargar', ['proyecto' => $proyecto, 'documento' => $documento]) }}" class="mt-3 block text-sm font-bold text-[#155AA3] underline">PDF #{{ $documento->id }} · {{ $documento->created_at->format('d/m/Y H:i') }}</a>@empty<p class="mt-3 text-sm text-slate-500">Todavía no se ha emitido un PDF final.</p>@endforelse</div>
    <a href="{{ $regreso['url'] }}" class="mt-6 inline-block rounded border border-[#155AA3] bg-white px-4 py-2 text-sm font-bold text-[#155AA3]">← {{ $regreso['etiqueta'] }}</a>
</x-contenedor-aplicacion>
